### ISSUE TITLE
Documentation Please

### ISSUE THREAD

**Issue by aliasav** [akshaymehra24/who-is-more-influential#34]
Can you guys please add some docs and comments, will be really helpful.

What would be totally awesome if you could write a tutorial kind of a blog post on this!

**Comment by akshaymehra24** [comment]
Hi Saurabh, I'll try to add some more documentation for this project. For code you can see https://github.com/akshaymehra24/who-is-more-influential/tree/master/Python. For our methodology may be this attachment will help.
[Predicting Influences in a Social Network - Final Report - v4.pdf](https://github.com/akshaymehra24/who-is-more-influential/files/1164651/Predicting.Influences.in.a.Social.Network.-.Final.Report.-.v4.pdf)

**Comment by aliasav** [comment]
Thanks a lot, the docs are a big help!
